/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseEchart: typeof import('./src/components/BaseEchart/index.vue')['default']
    Border1: typeof import('./src/components/BorderBox/border1.vue')['default']
    Border10: typeof import('./src/components/BorderBox/border10.vue')['default']
    Border11: typeof import('./src/components/BorderBox/border11.vue')['default']
    Border2: typeof import('./src/components/BorderBox/border2.vue')['default']
    Border3: typeof import('./src/components/BorderBox/border3.vue')['default']
    Border4: typeof import('./src/components/BorderBox/border4.vue')['default']
    Border5: typeof import('./src/components/BorderBox/border5.vue')['default']
    Border6: typeof import('./src/components/BorderBox/border6.vue')['default']
    Border7: typeof import('./src/components/BorderBox/border7.vue')['default']
    Border8: typeof import('./src/components/BorderBox/border8.vue')['default']
    Border9: typeof import('./src/components/BorderBox/border9.vue')['default']
    BorderBox: typeof import('./src/components/BorderBox/index.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb/index.vue')['default']
    CountTo: typeof import('./src/components/CountTo/index.vue')['default']
    Decorator: typeof import('./src/components/Decorator/index.vue')['default']
    Decorator1: typeof import('./src/components/Decorator/decorator1.vue')['default']
    Decorator2: typeof import('./src/components/Decorator/decorator2.vue')['default']
    DiaLog: typeof import('./src/components/DiaLog/index.vue')['default']
    DictTag: typeof import('./src/components/DictTag/index.vue')['default']
    FileUpload: typeof import('./src/components/FileUpload/index.vue')['default']
    HKVideo: typeof import('./src/components/MVideo/HKVideo.vue')['default']
    IconSelect: typeof import('./src/components/IconSelect/index.vue')['default']
    IFrame: typeof import('./src/components/iFrame/index.vue')['default']
    ImagePreview: typeof import('./src/components/ImagePreview/index.vue')['default']
    ModelFbx: typeof import('./src/components/VueThree/model-fbx.vue')['default']
    ModelGeneration: typeof import('./src/components/VueThree/model-generation.vue')['default']
    ModelGltf: typeof import('./src/components/VueThree/model-gltf.vue')['default']
    ModelJson: typeof import('./src/components/VueThree/model-json.vue')['default']
    ModelMixin: typeof import('./src/components/VueThree/model-mixin.vue')['default']
    ModelNodeEdit: typeof import('./src/components/VueThree/model-node-edit.vue')['default']
    ModelPanPicture: typeof import('./src/components/VueThree/model-PanPicture.vue')['default']
    MVideo: typeof import('./src/components/MVideo/index.vue')['default']
    Pagination: typeof import('./src/components/Pagination/index.vue')['default']
    ParentView: typeof import('./src/components/ParentView/index.vue')['default']
    PermissionBox: typeof import('./src/components/PromptBox/permissionBox.vue')['default']
    PromptBox: typeof import('./src/components/PromptBox/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    VideoVlc: typeof import('./src/components/MVideo/videoVlc.vue')['default']
    VideoWebrtc: typeof import('./src/components/MVideo/videoWebrtc.vue')['default']
  }
}
