/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Border1: typeof import('./src/components/BorderBox/border1.vue')['default']
    Border2: typeof import('./src/components/BorderBox/border2.vue')['default']
    Border3: typeof import('./src/components/BorderBox/border3.vue')['default']
    Border4: typeof import('./src/components/BorderBox/border4.vue')['default']
    BorderBox: typeof import('./src/components/BorderBox/index.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb/index.vue')['default']
    CountTo: typeof import('./src/components/CountTo/index.vue')['default']
    DeleteDialog: typeof import('./src/components/VueThree/ModelEdit/deleteDialog.vue')['default']
    DiaLog: typeof import('./src/components/DiaLog/index.vue')['default']
    EditArea: typeof import('./src/components/VueThree/ModelEdit/editArea.vue')['default']
    IFrame: typeof import('./src/components/iFrame/index.vue')['default']
    ImagePreview: typeof import('./src/components/ImagePreview/index.vue')['default']
    ModelEdit: typeof import('./src/components/VueThree/ModelEdit/index.vue')['default']
    ModelFbx: typeof import('./src/components/VueThree/model-fbx.vue')['default']
    ModelGeneration: typeof import('./src/components/VueThree/model-generation.vue')['default']
    ModelGltf: typeof import('./src/components/VueThree/model-gltf.vue')['default']
    ModelJson: typeof import('./src/components/VueThree/model-json.vue')['default']
    ModelMixin: typeof import('./src/components/VueThree/model-mixin.vue')['default']
    ModelPanPicture: typeof import('./src/components/VueThree/model-PanPicture.vue')['default']
    Pagination: typeof import('./src/components/Pagination/index.vue')['default']
    ParentView: typeof import('./src/components/ParentView/index.vue')['default']
    PromptBox: typeof import('./src/components/PromptBox/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    TablePage: typeof import('./src/components/TablePage/index.vue')['default']
    UniversalBody: typeof import('./src/components/UniversalBody/index.vue')['default']
  }
}
